### PR TITLE
Feature/standalone path update

### PR DESCRIPTION
**Pull request by christian-graf**
I adept the scripts to run the phpcs check and fix.

I changed the path to the vendor directory relative to the script file. 
Before the current working path of the caller was used. So it also works only within the project directory.

Now I can use the scripts also outside the project directory. 
I have adept this cause, I installed the scripts (via composer install) in my global php bin directory which is included within my system path.   Now I can use the scripts in all my projects (even older projects without composer) and use the sclable coding conventions.

I have tested it some days ago on my system. Should work fine :)

### CODE REVIEW

**Comment by christian-graf** [comment]
Mhmm ... the changes are not working on travis :(    ... I will check this in the next days!

**Comment by christian-graf** [comment]
Yeah, so I fixed the testing issues.

I implement a "search for the vendor directory" to fix this. Caus, within the testing environment the path is different to use the binaries in my package or application.

It is not the best way I think but maybe okay. 
Please check it - thanks!

**Comment by m-bymike** [comment]
Instead of searching the vendor dir in a while loop, a simple if / else would do the trick. There are only two possible locations for the autoload file, one for the development environment of the package and one when used as dependency.

```php
if (file_exists(dirname(__FILE__) . '/../vendor/autoload.php')) {
    require_once dirname(__FILE__) . '/../vendor/autoload.php';
} elseif (file_exists(dirname(__FILE__) . '/../../../autoload.php')) {
    require_once dirname(__FILE__) . '/../../../autoload.php';
} else {
 // Error
die('autoload.php not found');
}
```

**Comment by christian-graf** [comment]
Thanks for implement the feature!

**Pull request merged**
